apiVersion: v1
kind: ConfigMap
metadata:
  name: uc1-mqsc-ini
  namespace: cp4i
data:
  uniclus.mqsc: |-
    ALTER QMGR DEADQ('DLQ') REPOS(UNICLUS)
    DEFINE QLOCAL('DLQ') LIKE(SYSTEM.DEAD.LETTER.QUEUE) REPLACE
    DEFINE QLOCAL('DEV.QUEUE.1') DEFBIND(NOTFIXED) CLWLUSEQ(ANY) DEFPSIST(YES) REPLACE
    DEFINE QLOCAL('DEV.QUEUE.2') DEFBIND(NOTFIXED) CLWLUSEQ(ANY) DEFPSIST(YES) REPLACE
    DEFINE CHANNEL('UNICLUS_UC1') CHLTYPE(CLUSRCVR) TRPTYPE(TCP) CONNAME('uc1-ibm-mq.ibm-mq(1414)') CLUSTER('UNICLUS') SSLCAUTH(OPTIONAL) SSLCIPH('ANY_TLS12_OR_HIGHER') REPLACE
    DEFINE CHANNEL('UNICLUS_UC2') CHLTYPE(CLUSSDR) TRPTYPE(TCP) CONNAME('uc2-ibm-mq.ibm-mq(1414)') CLUSTER('UNICLUS') SSLCIPH('ANY_TLS12_OR_HIGHER') REPLACE
    DEFINE CHANNEL(APP.SVRCONN) CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCAUTH(OPTIONAL) SSLCIPH('ANY_TLS12_OR_HIGHER') REPLACE
    SET CHLAUTH(APP.SVRCONN) TYPE(BLOCKUSER) USERLIST(NOBODY)
    REFRESH SECURITY TYPE(CONNAUTH)
  uniclus.ini: |-
    AutoCluster:
      ClusterName=UNICLUS
      Type=Uniform
    SSL:
      OutboundSNI=HOSTNAME
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: uc2-mqsc-ini
  namespace: cp4i
data:
  uniclus.mqsc: |-
    ALTER QMGR DEADQ('DLQ') REPOS(UNICLUS)
    DEFINE QLOCAL('DLQ') LIKE(SYSTEM.DEAD.LETTER.QUEUE) REPLACE
    DEFINE QLOCAL('DEV.QUEUE.1') DEFBIND(NOTFIXED) CLWLUSEQ(ANY) DEFPSIST(YES) REPLACE
    DEFINE QLOCAL('DEV.QUEUE.2') DEFBIND(NOTFIXED) CLWLUSEQ(ANY) DEFPSIST(YES) REPLACE
    DEFINE CHANNEL('UNICLUS_UC2') CHLTYPE(CLUSRCVR) TRPTYPE(TCP) CONNAME('uc2-ibm-mq.ibm-mq(1414)') CLUSTER('UNICLUS') SSLCAUTH(OPTIONAL) SSLCIPH('ANY_TLS12_OR_HIGHER') REPLACE
    DEFINE CHANNEL('UNICLUS_UC1') CHLTYPE(CLUSSDR) TRPTYPE(TCP) CONNAME('uc1-ibm-mq.ibm-mq(1414)') CLUSTER('UNICLUS') SSLCIPH('ANY_TLS12_OR_HIGHER') REPLACE
    DEFINE CHANNEL(APP.SVRCONN) CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCAUTH(OPTIONAL) SSLCIPH('ANY_TLS12_OR_HIGHER') REPLACE
    SET CHLAUTH(APP.SVRCONN) TYPE(BLOCKUSER) USERLIST(NOBODY)
    REFRESH SECURITY TYPE(CONNAUTH)
  uniclus.ini: |-
    AutoCluster:
      ClusterName=UNICLUS
      Type=Uniform
    SSL:
      OutboundSNI=HOSTNAME
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: uc3-mqsc-ini
  namespace: cp4i
data:
  uniclus.mqsc: |-
    ALTER QMGR DEADQ('DLQ')
    DEFINE QLOCAL('DLQ') LIKE(SYSTEM.DEAD.LETTER.QUEUE) REPLACE
    DEFINE QLOCAL('DEV.QUEUE.1') DEFBIND(NOTFIXED) CLWLUSEQ(ANY) DEFPSIST(YES) REPLACE
    DEFINE QLOCAL('DEV.QUEUE.2') DEFBIND(NOTFIXED) CLWLUSEQ(ANY) DEFPSIST(YES) REPLACE
    DEFINE CHANNEL('UNICLUS_UC3') CHLTYPE(CLUSRCVR) TRPTYPE(TCP) CONNAME('uc3-ibm-mq.ibm-mq(1414)') CLUSTER('UNICLUS') SSLCAUTH(OPTIONAL) SSLCIPH('ANY_TLS12_OR_HIGHER') REPLACE
    DEFINE CHANNEL('UNICLUS_UC1') CHLTYPE(CLUSSDR) TRPTYPE(TCP) CONNAME('uc1-ibm-mq.ibm-mq(1414)') CLUSTER('UNICLUS') SSLCIPH('ANY_TLS12_OR_HIGHER') REPLACE
    DEFINE CHANNEL('UNICLUS_UC2') CHLTYPE(CLUSSDR) TRPTYPE(TCP) CONNAME('uc2-ibm-mq.ibm-mq(1414)') CLUSTER('UNICLUS') SSLCIPH('ANY_TLS12_OR_HIGHER') REPLACE
    DEFINE CHANNEL(APP.SVRCONN) CHLTYPE(SVRCONN) TRPTYPE(TCP) SSLCAUTH(OPTIONAL) SSLCIPH('ANY_TLS12_OR_HIGHER') REPLACE
    SET CHLAUTH(APP.SVRCONN) TYPE(BLOCKUSER) USERLIST(NOBODY)
    REFRESH SECURITY TYPE(CONNAUTH)
  uniclus.ini: |-
    AutoCluster:
      ClusterName=UNICLUS
      Type=Uniform
    SSL:
      OutboundSNI=HOSTNAME
