apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: entitlement
  annotations:
    argocd.argoproj.io/sync-wave: "300"
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: argocd
  source:
    repoURL: https://github.com/jorgenpersson59/mq-argo.git
    path: entitlement/resources
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
